# Generated by Django 5.0.6 on 2024-07-08 05:38

import appff.models
import appff.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=128, validators=[appff.validators.CustomPasswordValidator])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('mobile_number', models.CharField(max_length=15, validators=[appff.models.validate_mobile_number])),
                ('referral', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
